# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0002_auto_20160223_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='score',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
