# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 14:53
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0006_auto_20160227_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bitbucket_account',
            field=models.CharField(blank=True, max_length=32, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z', 32), "Enter a valid 'slug' consisting of letters, numbers, underscores or hyphens.", 'invalid')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bitbucket_repository',
            field=models.CharField(blank=True, max_length=32, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z', 32), "Enter a valid 'slug' consisting of letters, numbers, underscores or hyphens.", 'invalid')]),
        ),
    ]
