# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0007_auto_20160228_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='judged_by',
        ),
        migrations.AddField(
            model_name='submission',
            name='detail_message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('SU', 'Submitting'), ('SE', 'Submission Error'), ('CO', 'Compiling'), ('CE', 'Compilation Error'), ('JU', 'Judging'), ('AC', 'Accepted'), ('PA', 'Partially Accepted'), ('TL', 'Time Limit Exceeded'), ('ML', 'Memory Limit Exceeded'), ('RE', 'Runtime Error')], default='SU', max_length=2),
        ),
    ]
