# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-07 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0010_auto_20160306_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='memory_limit',
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('SU', 'Submitting'), ('SE', 'Submission Error'), ('CO', 'Compiling'), ('CE', 'Compilation Error'), ('JU', 'Judging'), ('AC', 'Accepted'), ('NA', 'Not Accepted'), ('TL', 'Time Limit Exceeded'), ('RE', 'Runtime Error')], db_index=True, default='SU', max_length=2),
        ),
    ]
