# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 22:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0011_auto_20160307_0340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='detail_messages',
            new_name='detailed_messages',
        ),
    ]
