# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 22:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0012_auto_20160309_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='time_limit',
        ),
    ]
