# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 00:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0014_auto_20160317_0044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='is_sample',
        ),
    ]
