# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0015_remove_problem_is_sample'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='Name', max_length=32),
            preserve_default=False,
        ),
    ]
