# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0016_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='detailed_messages_stderr',
            field=models.TextField(blank=True),
        ),
    ]
