# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-11 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0017_submission_detailed_messages_stderr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('SU', 'Submitting'), ('SE', 'Submission Error'), ('CO', 'Compiling'), ('CE', 'Compilation Error'), ('JU', 'Judging'), ('AC', 'Accepted'), ('WA', 'Wrong Answer'), ('RE', 'Runtime Error')], db_index=True, default='SU', max_length=2),
        ),
    ]
