# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-21 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0018_auto_20160411_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='solved_problems',
            field=models.ManyToManyField(blank=True, related_name='solved_profiles', to='judge.Problem'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('SU', 'Submitting'), ('SE', 'Submission Error'), ('CO', 'Compiling'), ('CE', 'Compilation Error'), ('JU', 'Judging'), ('AC', 'Accepted'), ('WA', 'Wrong Answer'), ('RE', 'Runtime Error')], default='SU', max_length=2),
        ),
    ]
