# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-05 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0019_auto_20160521_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='staff_viewable_only',
            field=models.BooleanField(default=False),
        ),
    ]
